@baseUrl = http://localhost:8000/api
@newTransactionId = i


### Get all transactions
# do not execute it because when a lot of records VSCode might crash
# GET {{baseUrl}}/transactions
# Accept: application/json

### Count all transactions
GET {{baseUrl}}/transactions/count

### Create new transaction

# @name createTransaction
POST {{baseUrl}}/transactions
Content-Type: application/json

{
  "date": "2015-09-24",
  "description": "ASEC W-wa Ratusz Ar/Warszawa",
  "amount": 1.70,
  "currency": "PLN",
  "category": "transport",
  "transactionType": "expense",
  "paymentMethod": "card",
  "account": "mBank",
  "currencies": "ABC/DEF",
  "exchangeRate": 1.6,
  "calcRefIdx": 1
}

### Get single transaction

@newTransactionId = {{createTransaction.response.body._id}}

GET {{baseUrl}}/transactions/{{newTransactionId}}
Accept: application/json

### Update a transaction (PUT)

PUT {{baseUrl}}/transactions/{{newTransactionId}} 
Content-Type: application/json

{ 
  "idx": 565,
  "date": "2015-09-24",
  "description": "ASEC W-wa Ratusz Ar/Warszawa some change",
  "amount": 2.70,
  "currency": "PLN",
  "category": "transport",
  "transactionType": "expense",
  "paymentMethod": "card",
  "account": "mBank",
  "currencies":null
  
}

### Partial update of transaction (PATCH)
PATCH {{baseUrl}}/transactions/{{newTransactionId}}
Content-Type: application/json

{
  "description": "ASEC W-wa Ratusz Ar/Warszawa another change",
  "amount": 7.77,
  "currencies": null
}

### Delete a transaction

DELETE {{baseUrl}}/transactions/{{newTransactionId}}


### Delete all transactions

DELETE {{baseUrl}}/transactions


### Import transactions CSV
POST http://localhost:8000/api/transactions/699719579344a89905cd5b60/import-csv
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="file"; filename="finance_all_transfer_refs.csv"
Content-Type: text/csv

< ../../../parser/data/all/finance_all_transfer_refs.csv
--boundary123--

# data with references for `myAccount` transactions
# finance_all_transfer_refs.csv

# migrated data which works well
# transactions-backup-2025-12-22T21-38-42-725Z.csv

# migrated data with broken reference
# transactions-backup-qwer-2025-12-22T21-11-34-725Z.csv

# data parsed from spredsheets
# finance_all.csv

# All expenses and incomes 8429 (till end of 2024)
# All expenses 7159
# All incomes 1270

# All expenses and incomes 9482 (till what I have for 2025 in spreadsheets
# All expenses 7929
# All incomes 1553

# 8630