@baseUrl = http://localhost:8000/api
@newTransactionId = i


### Get all transactions
GET {{baseUrl}}/transactions
Accept: application/json

### Create new transaction

# @name createTransaction
POST {{baseUrl}}/transactions
Content-Type: application/json

{
  "date": "2015-09-24",
  "description": "ASEC W-wa Ratusz Ar/Warszawa",
  "amount": 1.70,
  "currency": "PLN",
  "category": "transport",
  "transactionType": "expense",
  "paymentMethod": "card",
  "account": "mBank"
}

### Get single transaction

@newTransactionId = {{createTransaction.response.body._id}}

GET {{baseUrl}}/transactions/{{newTransactionId}}
Accept: application/json

### Update a transaction (PUT)

PUT {{baseUrl}}/transactions/{{newTransactionId}} 
Content-Type: application/json

{ 
  "idx": 567,
  "date": "2015-09-24",
  "description": "ASEC W-wa Ratusz Ar/Warszawa some change",
  "amount": 2.70,
  "currency": "PLN",
  "category": "transport",
  "transactionType": "expense",
  "paymentMethod": "card",
  "account": "mBank",
  "currencies": "ABC/DEF",
  "exchangeRate": 1.6,
  "calcRefIdx": 1
}

### Partial update of transaction (PATCH)
PATCH {{baseUrl}}/transactions/{{newTransactionId}}
Content-Type: application/json

{
  "description": "ASEC W-wa Ratusz Ar/Warszawa another change",
  "amount": 7.77
}

### Delete a transaction

DELETE {{baseUrl}}/transactions/{{newTransactionId}}


### Delete all transactions

DELETE {{baseUrl}}/transactions


### Import transactions CSV
POST http://localhost:8000/api/transactions/import-csv
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="file"; filename="finance_all.csv"
Content-Type: text/csv

< ../../../parser/data/all/finance_all.csv
--boundary123--

